name: Build Frontend and Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-frontend:
    name: Test Frontend Build (Node.js)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Test build (dry run)
        run: npm run build --dry-run

  build-backend:
  name: Test Backend Build (FastAPI/Python)
  runs-on: ubuntu-latest

  defaults:
    run:
      working-directory: ./backend

  steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ../requirements.txt
    - name: Test build (py_compile)
      run: python3 -m py_compile main.py
